version: '3.8'
volumes:
  mysql-data:
  public-data:
  tmp-data:
  log-data:

services:
  db:
    image: mysql:8.0.29
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    cap_add:
      - SYS_NICE

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: bundle exec puma -C config/puma.rb
    volumes:
      - ./backend:/divwork
      - ./backend/vendor/bundle:/divwork/vendor/bundle
      - public-data:/divwork/public
      - tmp-data:/divwork/tmp
      - log-data:/divwork/log
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
    ports:
      - '3000:3000'
    depends_on:
      - db
    stdin_open: true
    tty: true

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: ash -c "yarn start"
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - '3001:3000'
    stdin_open: true
    tty: true

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - public-data:/divwork/public
      - tmp-data:/divwork/tmp
    ports:
      - 80:80
    depends_on:
      - backend
