version: '3.8'
volumes:
  puma-sock:

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    volumes:
      - type: bind
        source: ./frontend/build
        target: /var/www/frontend/build
        consistency: cached
      - type: volume
        source: puma-sock
        target: /var/www/backend/tmp/sockets
        volume:
          nocopy: true
    ports:
      - 80:80

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    command: bundle exec puma -e development
    volumes:
      - type: bind
        source: ./backend
        target: /var/www/backend
        consistency: cached
      - type: bind
        source: ~/.ssh
        target: /root/.ssh
        consistency: cached
      - type: volume
        source: puma-sock
        target: /var/www/backend/tmp/sockets
        volume:
          nocopy: true
    environment:
      TZ: Asia/Tokyo
      # RAILS_ENV: production
    ports:
      - '3001:3001'

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    command: ash -c "yarn start"
    volumes:
      - type: bind
        source: ./frontend/build
        target: /var/www/frontend/build
        consistency: cached
    ports:
      - '3000:3000'
