require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - "bin/*"
    - "db/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
  TargetRubyVersion: 3.1.2

Rails/FilePath:
  Exclude:
    - "config/environments/development.rb"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Enabled: false

Layout/LineLength:
  Exclude:
    - "config/initializers/devise.rb"

Style/WordArray:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
