name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  rspec:
    name: RSpec
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
    defaults:
      run:
        working-directory: backend
    services:
      mysql:
        image: mysql:8.0.29
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          BIND-ADDRESS: 0.0.0.0
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 10
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'
          bundler-cache: true
      - name: Run bundle install
        run: |
          bundle config --local path vendor/bundle
          bundle install
      - name: Run migration
        run: |
          bundle exec rails db:create
          bundle exec rails db:test:prepare
      - name: Run RSpec
        run: bundle exec rspec
