name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  rspec:
    name: RSpec
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'
      - name: Run bundle install
        run: |
          bundle config --local path vendor/bundle
          bundle install
      - name: Run RSpec
        run: bundle exec rspec
